name: Base

on:
  workflow_call:
    inputs:
      search_query:
        required: true
        type: string
      template_name:
        required: true
        type: string
      template_repo:
        required: true
        type: string
      version:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.11.0'

      - name: Install packages
        run: npm install
        shell: sh

      # This should be performed before 'Comment as markdown'
      #   https://github.com/noraworld/to-do/issues/1807
      #   https://github.com/noraworld/diary-templates-assistant/actions/runs/16912208720/job/47916650024
      #   https://github.com/noraworld/diary-templates-assistant/actions/runs/17118740677/job/48554795096
      - name: Comment as JSON Lines
        run: node app/jsonl.js
        shell: sh
        env:
          GH_TOKEN: ${{ secrets.token }}
          PARTIAL_CONTENT_START_STRING: '(<span dir=\"auto\">{private}|<div dir=\"auto\"><p>{private})'
          PARTIAL_CONTENT_END_STRING: '({/private}</span>|{/private}</div>)'
          SEARCH_QUERY: 'db データベース'
          TEMPLATE_NAME: ${{ inputs.template_name }}
          TEMPLATE_REPO: ${{ inputs.template_repo }}
          VERSION: ${{ inputs.version }}

      - name: Comment as markdown
        run: node app/comment_from_dispatch.js
        shell: sh
        env:
          GH_TOKEN: ${{ secrets.token }}
          SEARCH_QUERY: ${{ inputs.search_query }}
          TEMPLATE_NAME: ${{ inputs.template_name }}
          TEMPLATE_REPO: ${{ inputs.template_repo }}
