# See also: .github/workflows/batch-work.yml

name: '001: Issue Refresh Batch (personal)'

on:
  workflow_dispatch:
    inputs:
      fail_on_unsuccessful:
        required: true
        description: 'Fail when a reusable workflow reports unsuccessful'
        type: choice
        options:
          - 'true'
          - 'false'
        default: 'true'
      timezone:
        required: true
        description: 'Timezone'
        type: choice
        options:
          # https://gist.github.com/diogocapela/12c6617fc87607d11fd62d2a4f42b02a
          - ''
          - 'Etc/Universal'
          - 'Asia/Tokyo'
          - 'Australia/Sydney'
        # Comment #1
        #   When it is performed by workflow_dispatch, this default value will be referenced
        #   instead of 'foo' in '${{ github.event.inputs.timezone || 'foo' }}'.
        #   See also Comment #2.
        default: 'Asia/Tokyo'
  schedule:
    # Read this if you want to delay the time to change the diary issues.
    #   https://github.com/noraworld/reserved-diary/issues/708#issuecomment-2790207338
    #   https://github.com/noraworld/reserved-diary/issues/708#issuecomment-2790217630
    #   https://github.com/noraworld/reserved-diary/issues/708#issuecomment-2790220599
    # JST: 07:50 AM
    - cron: '50 22 * * *'

jobs:
  # reserved-diary
  comments-transferor-force:
    uses: noraworld/social-media-recorder/.github/workflows/comments-transferor-force.yml@main
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}

  templates-closer:
    needs: comments-transferor-force
    uses: noraworld/diary-templates-assistant/.github/workflows/templates-closer.yml@main
    with:
      repo: noraworld/diary-templates
      # Comment #2
      #   The value after '||' is only referenced in cron.
      #   See also Comment #1.
      fail_on_unsuccessful: ${{ github.event_name == 'schedule' && 'true' || github.event.inputs.fail_on_unsuccessful }}
      timezone: ${{ github.event.inputs.timezone || 'Asia/Tokyo' }}
      date_check: true
    secrets:
      token: ${{ secrets.GH_TOKEN }}

  wait-for-templates-closed:
    needs: templates-closer
    if: needs.templates-closer.outputs.succeeded == 'true'
    uses: noraworld/diary-templates-assistant/.github/workflows/wait-closed.yml@main
    with:
      template_repo: noraworld/diary-templates
    secrets:
      token: ${{ secrets.GH_TOKEN }}

  convert-unchecked:
    needs: wait-for-templates-closed
    uses: noraworld/diary-templates-assistant/.github/workflows/convert-unchecked.yml@main
    with:
      main_repo: noraworld/reserved-diary
    secrets:
      token: ${{ secrets.GH_TOKEN }}

  issue-changer:
    needs: convert-unchecked
    uses: noraworld/diary-templates-assistant/.github/workflows/issue-changer.yml@main
    with:
      main_repo: noraworld/reserved-diary
      fail_on_unsuccessful: ${{ github.event_name == 'schedule' && 'true' || github.event.inputs.fail_on_unsuccessful }}
      template_repo: noraworld/diary-templates
      timezone: ${{ github.event.inputs.timezone || 'Asia/Tokyo' }}
    secrets:
      token: ${{ secrets.GH_TOKEN }}

  templates-creator:
    needs: issue-changer
    if: needs.issue-changer.outputs.succeeded == 'true'
    uses: noraworld/diary-templates-assistant/.github/workflows/templates-creator.yml@main
    with:
      fail_on_unsuccessful: ${{ github.event_name == 'schedule' && 'true' || github.event.inputs.fail_on_unsuccessful }}
      main_repo: noraworld/reserved-diary
      template_repo: noraworld/diary-templates
      issue_template_repo: noraworld/diary-templates-assistant
      timezone: ${{ github.event.inputs.timezone || 'Asia/Tokyo' }}
    secrets:
      token: ${{ secrets.GH_TOKEN }}

  templates-linker:
    needs: templates-creator
    if: needs.templates-creator.outputs.succeeded == 'true'
    uses: noraworld/diary-templates-assistant/.github/workflows/templates-linker.yml@main
    with:
      main_repo: noraworld/reserved-diary
      template_repo: noraworld/diary-templates
      timezone: ${{ github.event.inputs.timezone || 'Asia/Tokyo' }}
    secrets:
      token: ${{ secrets.GH_TOKEN }}



  # private-diary
  private-templates-closer:
    needs: templates-linker
    uses: noraworld/diary-templates-assistant/.github/workflows/templates-closer.yml@main
    with:
      repo: noraworld/private-diary-templates
      fail_on_unsuccessful: ${{ github.event_name == 'schedule' && 'true' || github.event.inputs.fail_on_unsuccessful }}
      timezone: ${{ github.event.inputs.timezone || 'Asia/Tokyo' }}
      date_check: true
    secrets:
      token: ${{ secrets.GH_TOKEN }}

  private-wait-for-templates-closed:
    needs: private-templates-closer
    if: needs.private-templates-closer.outputs.succeeded == 'true'
    uses: noraworld/diary-templates-assistant/.github/workflows/wait-closed.yml@main
    with:
      template_repo: noraworld/private-diary-templates
    secrets:
      token: ${{ secrets.GH_TOKEN }}

  private-convert-unchecked:
    needs: private-wait-for-templates-closed
    uses: noraworld/diary-templates-assistant/.github/workflows/convert-unchecked.yml@main
    with:
      main_repo: noraworld/private-diary
    secrets:
      token: ${{ secrets.GH_TOKEN }}

  private-issue-changer:
    needs: private-convert-unchecked
    uses: noraworld/diary-templates-assistant/.github/workflows/issue-changer.yml@main
    with:
      main_repo: noraworld/private-diary
      fail_on_unsuccessful: ${{ github.event_name == 'schedule' && 'true' || github.event.inputs.fail_on_unsuccessful }}
      template_repo: noraworld/private-diary-templates
      timezone: ${{ github.event.inputs.timezone || 'Asia/Tokyo' }}
    secrets:
      token: ${{ secrets.GH_TOKEN }}

  private-templates-creator:
    needs: private-issue-changer
    if: needs.private-issue-changer.outputs.succeeded == 'true'
    uses: noraworld/diary-templates-assistant/.github/workflows/templates-creator.yml@main
    with:
      fail_on_unsuccessful: ${{ github.event_name == 'schedule' && 'true' || github.event.inputs.fail_on_unsuccessful }}
      main_repo: noraworld/private-diary
      template_repo: noraworld/private-diary-templates
      issue_template_repo: noraworld/private-diary-templates
      timezone: ${{ github.event.inputs.timezone || 'Asia/Tokyo' }}
    secrets:
      token: ${{ secrets.GH_TOKEN }}

  private-templates-linker:
    needs: private-templates-creator
    if: needs.private-templates-creator.outputs.succeeded == 'true'
    uses: noraworld/diary-templates-assistant/.github/workflows/templates-linker.yml@main
    with:
      main_repo: noraworld/private-diary
      template_repo: noraworld/private-diary-templates
      timezone: ${{ github.event.inputs.timezone || 'Asia/Tokyo' }}
    secrets:
      token: ${{ secrets.GH_TOKEN }}
