name: '611: 🧹📨 デジタルハウスキーピング'

on:
  workflow_dispatch:
    inputs:
      impression:
        required: false
        description: '感想・その他'
        type: string
      scanned:
        required: true
        description: '書類スキャン'
        type: boolean
      organized:
        required: true
        description: '書類整理'
        type: boolean
      mail:
        required: true
        description: 'メールチェック'
        type: boolean

jobs:
  chore:
    uses: noraworld/diary-templates-assistant/.github/workflows/base.yml@main
    with:
      search_query: "chore デジタルハウスキーピング"
      template_name: "chore"
      template_repo: "noraworld/diary-templates"
      version: "0.1.0"
    secrets:
      token: ${{ secrets.GH_TOKEN }}
