name: '261: 🎓📎 クリッピング'

on:
  workflow_dispatch:
    inputs:
      site1:
        required: true
        description: 'サイト 1（リンク付き）'
        type: string
      category:
        required: true
        description: 'タグ'
        type: choice
        options:
          - ''
          - 'YouTube'
          - 'dotinstall'
          - 'ChatGPT'
          - '技術記事'
          - 'パレオな男'
          - 'D ラボ'
          - 'Amazon Prime'
          - 'Netflix'
          - 'AbemaTV'
          - 'ニコニコ動画'
          - 'ブログ'
          - 'ウェブ記事'
      impression:
        required: false
        description: '感想'
        type: string
      progress:
        required: false
        description: '進捗率（動画の例: "12:34"）'
        type: string
      site2:
        required: false
        description: 'サイト 2（リンク付き）'
        type: string
      site3:
        required: false
        description: 'サイト 3（リンク付き）'
        type: string
      site4:
        required: false
        description: 'サイト 4（リンク付き）'
        type: string
      site5:
        required: false
        description: 'サイト 5（リンク付き）'
        type: string
      site6:
        required: false
        description: 'サイト 6（リンク付き）'
        type: string
      site7:
        required: false
        description: 'サイト 7（リンク付き）'
        type: string

jobs:
  clippings:
    uses: noraworld/diary-templates-assistant/.github/workflows/base.yml@main
    with:
      search_query: "clippings クリッピング"
      template_name: "clippings"
      template_repo: "noraworld/diary-templates"
      version: "0.2.3"
    secrets:
      token: ${{ secrets.GH_TOKEN }}
