name: Convert Unchecked

on:
  workflow_call:
    inputs:
      main_repo:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - run: |
          NUMBER=$(gh issue list --repo "$MAIN_REPO" --limit 1 | awk '{ print $1 }')
          BODY=$(gh issue view --repo "$MAIN_REPO" --json body --jq .body "$NUMBER")
          BODY_WITHOUT_UNCHECKED_TASK=$(echo "$BODY" | sed -E "s/^\* *\[ \] (.*)/\* \1/g")

          gh issue edit --repo "$MAIN_REPO" --body "$BODY_WITHOUT_UNCHECKED_TASK" "$NUMBER"
          UNCHECKED_TASK_COUNT=$(gh issue view --repo "$MAIN_REPO" --json body --jq .body "$NUMBER" | grep -cE "^\* *\[ \]" || true)

          if [ "$UNCHECKED_TASK_COUNT" -ne 0 ]; then
            echo "ERROR: there are some unchecked tasks!" >&2
            exit 1
          fi
        shell: sh
        env:
          MAIN_REPO: ${{ inputs.main_repo }}
          GH_TOKEN: ${{ secrets.token }}
