name: Day Off

on:
  workflow_dispatch:
    inputs:
      timezone:
        required: true
        description: 'Timezone'
        type: choice
        options:
          - ''
          - 'Etc/Universal'
          - 'Asia/Tokyo'
          - 'Australia/Sydney'
        default: 'Asia/Tokyo'
  workflow_call:
    inputs:
      timezone:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
          cache: 'pipenv'

      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python

      - name: Install packages
        run: pipenv install

      - name: Check if today is a day off or a holiday
        run: pipenv run python app/day-off.py
        shell: sh
        env:
          TZ: ${{ inputs.timezone || github.event.inputs.timezone }}
