name: '352: 🌿💩 排泄記録 / 排便'

on:
  workflow_dispatch:
    inputs:
      shape:
        required: true
        description: 'かたち'
        type: choice
        options:
          - ''
          - 'ころころ'
          - 'かちかち'
          - 'ぶりぶり'
          - 'ほそほそ'
          - 'ふわふわ'
          - 'どろどろ'
          - 'びちびち'
      color:
        required: true
        description: '色'
        type: choice
        options:
          - ''
          - '⚪️ マシュマロ'
          - '🟡 レモン'
          - '🟠 オレンジ'
          - '🟤 かつおぶし'
          - '🟤 カレー'
          - '🟤 チョコレート'
          - '🟢 もろへいや'
          - '⚫️ いかすみ'
          - '🔴 ハバネロ'
      amount:
        required: true
        description: '量（g）'
        type: choice
        options:
          - ''
          - '50'
          - '100'
          - '200'
          - '300'
          - '350'
      smell:
        required: true
        description: 'におい'
        type: choice
        options:
          - ''
          - '🤭 くさくない'
          - '😵 ちょっとくさい'
          - '😵‍💫 くさい'
          - '🤮 とてもくさい'
      relief:
        required: true
        description: 'すっきり感'
        type: choice
        options:
          - ''
          - '😌 すっきり'
          - '☹️ ちょい残り'
          - '🤢 苦しい'
      minutes:
        required: true
        description: '時間（分）'
        type: choice
        options:
          - ''
          - '5'
          - '10'
          - '15'
          - '20'
          - '25'
          - '30'
      impression:
        required: false
        description: 'メモ'
        type: string
      float:
        required: true
        description: 'ぷかぷか'
        type: boolean
      pain:
        required: true
        description: 'はらいた'
        type: boolean

jobs:
  defecation:
    uses: noraworld/diary-templates-assistant/.github/workflows/base.yml@main
    with:
      search_query: "excretion 排泄記録"
      template_name: "defecation"
      template_repo: "noraworld/diary-templates"
      version: "0.3.0"
    secrets:
      token: ${{ secrets.GH_TOKEN }}
