name: '631: 🧹💰 入出金履歴チェック'

on:
  workflow_dispatch:
    inputs:
      impression:
        required: false
        description: '分析・所感'
        type: string
      expense1:
        required: false
        description: '支出 1'
        type: string
      reasonable1:
        required: false
        description: '妥当性 1'
        type: choice
        options:
          - ''
          - '😉 妥当'
          - '🤔 微妙'
          - '☹️ 無駄'
      expense2:
        required: false
        description: '支出 2'
        type: string
      reasonable2:
        required: false
        description: '妥当性 2'
        type: choice
        options:
          - ''
          - '😉 妥当'
          - '🤔 微妙'
          - '☹️ 無駄'
      expense3:
        required: false
        description: '支出 3'
        type: string
      reasonable3:
        required: false
        description: '妥当性 3'
        type: choice
        options:
          - ''
          - '😉 妥当'
          - '🤔 微妙'
          - '☹️ 無駄'
      expense4:
        required: false
        description: '支出 4'
        type: string
      reasonable4:
        required: false
        description: '妥当性 4'
        type: choice
        options:
          - ''
          - '😉 妥当'
          - '🤔 微妙'
          - '☹️ 無駄'
      notification:
        required: true
        description: '未確定入出金を既読にした？'
        type: choice
        options:
          - ''
          - 'はい'

jobs:
  finance:
    uses: noraworld/diary-templates-assistant/.github/workflows/base.yml@main
    with:
      search_query: "finance 入出金履歴チェック"
      template_name: "finance"
      template_repo: "noraworld/diary-templates"
      version: "0.1.0"
    secrets:
      token: ${{ secrets.GH_TOKEN }}
