name: '322: 🌿🥗 食事記録（選択・健康）'

on:
  workflow_dispatch:
    inputs:
      food:
        required: true
        description: '食べたもの'
        type: choice
        options:
          - ''
          - '💪'
          - 'バナナ'
          - 'プロテイン'
          - 'サラダチキン'
          - 'しっとりプレーン サラダチキン'
          - '爽やかバジル サラダチキン'
          - '生卵'
          - 'ゆで卵'
          - '🥜'
          - 'ミックスナッツ'
          - 'チョコレート効果 カカオ95%'
          - '🥗'
          - 'キムチ'
          - 'キャベツ'
          - 'コールスロー'
          - 'キャベツミックス'
          - 'シャキシャキ千切りキャベツ'
          - '千切りキャベツのミックスサラダ'
          - '天使のキャベツを使った千切りキャベツ'
          - '食べやすく育てたスプラウトと細切にした野菜のおいしいサラダ'
          - '冷凍ブロッコリー'
          - '🐟'
          - 'サーモン'
          - 'カツオ'
          - 'ブリ'
          - 'マグロ'
          - 'メバチマグロ'
          - 'さば水煮'
          - 'オイル不使用 シーチキン マイルド'
          - '納豆'
          - '豆腐'
          - '🍚'
          - '白米'
          - '玄米'
          - '焼き芋'
          - '🫐'
          - '冷凍ブルーベリー'
          - 'ネーブルオレンジ'
          - 'みかん'
          - 'いちご'
          - 'ゴールドキウイ'
          - '紅ほっぺ'
          - 'ギリシャヨーグルト'
      category:
        required: true
        description: '分類'
        type: choice
        # 上記の「食べたもの」をそのまま分類に変換して隣り合って重複している部分を取り除く
        options:
          - ''
          - '💪'
          - 'フルーツ'
          - 'プロテイン'
          - '鶏肉'
          - '鶏卵'
          - '🥜'
          - 'ナッツ'
          - 'ダークチョコレート'
          - '🥗'
          - '野菜'
          - '🐟'
          - '魚'
          - '豆'
          - '豆腐'
          - '🍚'
          - '白米'
          - '玄米'
          - 'さつまいも'
          - '🫐'
          - 'フルーツ'
          - 'ヨーグルト'
      quantity:
        required: true
        description: '分量'
        type: number
      unit:
        required: true
        description: '単位'
        type: choice
        options:
          - ''
          - '人前'
          - '個'
          - '本'
          - '杯'
          - '袋'
          - '箱'
          - 'パック'
          - 'g'
          - 'ml'
      score:
        required: true
        description: 'MIND スコア'
        type: choice
        options:
          - ''
          - '0'
          - '+1'
          - '+2'
          - '+3'
          - '+4'
          - '+5'
          - ''
          - '-1'
          - '-3'
          - '-5'
      seasoning:
        required: false
        description: '調味料'
        type: choice
        options:
          - ''
          - 'エクストラヴァージンオリーブオイル'
          - 'ドレッシング'
          - '塩'
          - '醤油'
          - 'はちみつ'
          - '納豆のタレ'
          - 'カラシ'
      impression:
        required: false
        description: '感想'
        type: string

jobs:
  food:
    uses: noraworld/diary-templates-assistant/.github/workflows/base.yml@main
    with:
      search_query: "food 食事記録"
      template_name: "food-eaten"
      template_repo: "noraworld/diary-templates"
      version: "0.2.5"
    secrets:
      token: ${{ secrets.GH_TOKEN }}
