name: '321: 🌿🥗 食事記録 / 食べたもの（記述式）'

on:
  workflow_dispatch:
    inputs:
      food:
        required: true
        description: '食べたもの'
        type: string
      category:
        required: true
        description: '分類'
        type: string
      quantity:
        required: true
        description: '分量'
        type: number
      unit:
        required: true
        description: '単位'
        type: choice
        options:
          - ''
          - '人前'
          - '個'
          - '本'
          - '杯'
          - '袋'
          - '箱'
          - 'g'
      impression:
        required: false
        description: '感想'
        type: string

jobs:
  food:
    uses: noraworld/diary-templates-assistant/.github/workflows/base.yml@main
    with:
      search_query: "food 食事記録"
      template_name: "food-eaten"
      template_repo: "noraworld/diary-templates"
      version: "0.2.3"
    secrets:
      token: ${{ secrets.GH_TOKEN }}
