name: '324: 🌿🥗 食事記録 / 基本情報'

on:
  workflow_dispatch:
    inputs:
      saffron:
        required: true
        description: 'サフランカプセル'
        type: boolean
      impression:
        required: false
        description: '分析・所感'
        type: string
      notification:
        required: true
        description: '写真を忘れずに'
        type: choice
        options:
          - ''
          - 'わかった'

jobs:
  food:
    uses: noraworld/diary-templates-assistant/.github/workflows/base.yml@main
    with:
      search_query: "food 食事記録"
      template_name: "food-basic"
      template_repo: "noraworld/diary-templates"
      version: "0.1.0"
    secrets:
      token: ${{ secrets.GH_TOKEN }}
