name: '726: 🧹🧼🧴 衛生'

on:
  workflow_dispatch:
    inputs:
      minutes:
        required: false
        description: '分'
        type: number
      seconds:
        required: false
        description: '秒'
        type: number
      note:
        required: false
        description: 'メモ'
        type: string
      toys1:
        required: false
        description: '使用器具 1'
        type: string
      toys2:
        required: false
        description: '使用器具 2'
        type: string
      toys3:
        required: false
        description: '使用器具 3'
        type: string
      toys4:
        required: false
        description: '使用器具 4'
        type: string
      toys5:
        required: false
        description: '使用器具 5'
        type: string
      toys6:
        required: false
        description: '使用器具 6'
        type: choice
        options:
          - ''
          - 'セブンティーン'
          - 'atom リング小'
          - 'atom リング大'
      toys7:
        required: false
        description: '使用器具 7'
        type: choice
        options:
          - ''
          - 'セブンティーン'
          - 'atom リング小'
          - 'atom リング大'
      toys8:
        required: false
        description: '使用器具 8'
        type: choice
        options:
          - ''
          - 'セブンティーン'
          - 'atom リング小'
          - 'atom リング大'
      toys9:
        required: false
        description: '使用器具 9'
        type: choice
        options:
          - ''
          - 'セブンティーン'
          - 'atom リング小'
          - 'atom リング大'
      toys10:
        required: false
        description: '使用器具 10'
        type: choice
        options:
          - ''
          - 'セブンティーン'
          - 'atom リング小'
          - 'atom リング大'
      toys11:
        required: false
        description: '使用器具 11'
        type: choice
        options:
          - ''
          - 'セブンティーン'
          - 'atom リング小'
          - 'atom リング大'
      toys12:
        required: false
        description: '使用器具 12'
        type: choice
        options:
          - ''
          - 'セブンティーン'
          - 'atom リング小'
          - 'atom リング大'
      toys13:
        required: false
        description: '使用器具 13'
        type: choice
        options:
          - ''
          - 'セブンティーン'
          - 'atom リング小'
          - 'atom リング大'
      toys14:
        required: false
        description: '使用器具 14'
        type: choice
        options:
          - ''
          - 'セブンティーン'
          - 'atom リング小'
          - 'atom リング大'
      toys15:
        required: false
        description: '使用器具 15'
        type: choice
        options:
          - ''
          - 'セブンティーン'
          - 'atom リング小'
          - 'atom リング大'

jobs:
  hygiene:
    uses: noraworld/diary-templates-assistant/.github/workflows/base.yml@main
    with:
      search_query: "housework 家事"
      template_name: "hygiene"
      template_repo: "noraworld/diary-templates"
      version: "0.1.2"
    secrets:
      token: ${{ secrets.GH_TOKEN }}
