name: Issue Changer

# 8:00 AM (JST) every day
on:
  schedule:
    - cron: '0 22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Change issues
        # Note that the timezone is UTC.
        run: |
          TEMPLATE=$(cat GH_ISSUE_TEMPLATES.md)
          TO_DO_TOMORROW=$(gh issue list \
          --repo noraworld/to-do \
          --label tomorrow \
          --json title,url \
          --template '{{"\r\n"}}{{range.}}* [ ] [{{.title}}]({{.url}}){{"\r\n"}}{{end}}')
          TO_DO_TODAY=$(gh issue list \
          --repo noraworld/to-do \
          --label today \
          --json title,url \
          --template '{{range.}}* [ ] [{{.title}}]({{.url}}){{"\r\n"}}{{end}}')

          gh issue create --title "$(date '+%Y-%m-%d' --date '1 day')" --body "$TEMPLATE$TO_DO_TOMORROW$TO_DO_TODAY"
          gh issue list --search $(date '+%Y-%m-%d') | awk '{ print $1 }' | xargs -I {} gh issue close {}
        shell: sh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
