name: Issue Changer

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Change issues
        run: |
          if [ "$(gh issue list --repo "noraworld/diary-templates" | wc -l)" -ne 0 ]; then
            echo "Some of or all of the diary templates have not been closed yet." >&2
            exit 1
          fi

          ISSUE_TEMPLATE=$(gh api "/repos/noraworld/diary/contents/.github/ISSUE_TEMPLATE/general.md" \
                           --jq .content                                                              |
                           base64 --decode)
          ISSUE_TITLE_LIST=$(gh issue list --repo "noraworld/diary" --json title --jq .[].title)

          title=$(echo "$ISSUE_TEMPLATE"                                        |
                  grep "title: "                                                |
                  sed -e 's/^title: //g'                                        |
                  sed -e "s/[\"\']//g"                                          |
                  sed -e "s/\[{{DATE}}\]/$(date '+%Y-%m-%d' --date '1 day')/g")

          if [ "$(echo "$ISSUE_TITLE_LIST" | grep -c "$title")" -ne 0 ]; then
            echo "It will be skipped because \"$title\" already exists." >&2
            exit 1
          fi

          body=$(echo "$ISSUE_TEMPLATE" | sed -e '/^---$/,/^---$/d')

          TO_DO=$(gh issue list                                                                         \
                  --repo noraworld/to-do                                                                \
                  --search "label:today,tomorrow"                                                       \
                  --json title,url                                                                      \
                  --template '{{range.}}* [ ] [{{.title}}]({{.url}}){{"\r\n"}}{{end}}{{"\r\n"}}' | tac)

          processed_body="$body"
          if [ "$(echo "$TO_DO" | tr -d "\n" | tr -d "\r" | tr -d "\r\n")" != "" ]; then
            processed_body=$(echo "$processed_body" | sed -E 's/\* 特になし//g')
            processed_body="$processed_body$TO_DO"
          fi

          assignee=$(echo "$ISSUE_TEMPLATE" | grep "assignees: " |
                     sed -e 's/^assignees: //g'                  |
                     sed -e "s/[\"\']//g")

          url=$(gh issue create            \
                  --repo "noraworld/diary" \
                  --title "$title"         \
                  --body "$processed_body" \
                  --assignee "$assignee")

          gh issue list                  \
            --repo "noraworld/diary"     \
            --search $(date '+%Y-%m-%d') |
            awk '{ print $1 }'           |
            xargs -I {} gh issue close {} --repo "noraworld/diary"
        shell: sh
        env:
          GH_TOKEN: ${{ secrets.token }}
