name: '723: 🧹🧼👕 洗濯'

on:
  workflow_dispatch:
    inputs:
      # minutes:
      #   required: false
      #   description: '分'
      #   type: number
      # seconds:
      #   required: false
      #   description: '秒'
      #   type: number
      note:
        required: false
        description: 'メモ'
        type: string
      clothes1:
        required: false
        description: '衣類 1'
        type: string
      clothes2:
        required: false
        description: '衣類 2'
        type: string
      clothes3:
        required: false
        description: '衣類 3'
        type: string
      clothes4:
        required: false
        description: '衣類 4'
        type: string
      clothes5:
        required: false
        description: '衣類 5'
        type: string
      clothes6:
        required: false
        description: '衣類 6'
        type: choice
        options:
          - ''
          - '下着'
          - '靴下'
          - 'シャツ'
          - '上着'
          - '部屋着用ズボン'
          - '外出用ズボン'
          - '手拭きタオル'
          - 'バスタオル'
          - 'アイマスク'
          - 'まくらカバー'
          - 'シーツ'
      clothes7:
        required: false
        description: '衣類 7'
        type: choice
        options:
          - ''
          - '下着'
          - '靴下'
          - 'シャツ'
          - '上着'
          - '部屋着用ズボン'
          - '外出用ズボン'
          - '手拭きタオル'
          - 'バスタオル'
          - 'アイマスク'
          - 'まくらカバー'
          - 'シーツ'
      clothes8:
        required: false
        description: '衣類 8'
        type: choice
        options:
          - ''
          - '下着'
          - '靴下'
          - 'シャツ'
          - '上着'
          - '部屋着用ズボン'
          - '外出用ズボン'
          - '手拭きタオル'
          - 'バスタオル'
          - 'アイマスク'
          - 'まくらカバー'
          - 'シーツ'
      clothes9:
        required: false
        description: '衣類 9'
        type: choice
        options:
          - ''
          - '下着'
          - '靴下'
          - 'シャツ'
          - '上着'
          - '部屋着用ズボン'
          - '外出用ズボン'
          - '手拭きタオル'
          - 'バスタオル'
          - 'アイマスク'
          - 'まくらカバー'
          - 'シーツ'
      clothes10:
        required: false
        description: '衣類 10'
        type: choice
        options:
          - ''
          - '下着'
          - '靴下'
          - 'シャツ'
          - '上着'
          - '部屋着用ズボン'
          - '外出用ズボン'
          - '手拭きタオル'
          - 'バスタオル'
          - 'アイマスク'
          - 'まくらカバー'
          - 'シーツ'
      clothes11:
        required: false
        description: '衣類 11'
        type: choice
        options:
          - ''
          - '下着'
          - '靴下'
          - 'シャツ'
          - '上着'
          - '部屋着用ズボン'
          - '外出用ズボン'
          - '手拭きタオル'
          - 'バスタオル'
          - 'アイマスク'
          - 'まくらカバー'
          - 'シーツ'
      clothes12:
        required: false
        description: '衣類 12'
        type: choice
        options:
          - ''
          - '下着'
          - '靴下'
          - 'シャツ'
          - '上着'
          - '部屋着用ズボン'
          - '外出用ズボン'
          - '手拭きタオル'
          - 'バスタオル'
          - 'アイマスク'
          - 'まくらカバー'
          - 'シーツ'
      clothes13:
        required: false
        description: '衣類 13'
        type: choice
        options:
          - ''
          - '下着'
          - '靴下'
          - 'シャツ'
          - '上着'
          - '部屋着用ズボン'
          - '外出用ズボン'
          - '手拭きタオル'
          - 'バスタオル'
          - 'アイマスク'
          - 'まくらカバー'
          - 'シーツ'
      clothes14:
        required: false
        description: '衣類 14'
        type: choice
        options:
          - ''
          - '下着'
          - '靴下'
          - 'シャツ'
          - '上着'
          - '部屋着用ズボン'
          - '外出用ズボン'
          - '手拭きタオル'
          - 'バスタオル'
          - 'アイマスク'
          - 'まくらカバー'
          - 'シーツ'
      clothes15:
        required: false
        description: '衣類 15'
        type: choice
        options:
          - ''
          - '下着'
          - '靴下'
          - 'シャツ'
          - '上着'
          - '部屋着用ズボン'
          - '外出用ズボン'
          - '手拭きタオル'
          - 'バスタオル'
          - 'アイマスク'
          - 'まくらカバー'
          - 'シーツ'

jobs:
  laundry:
    uses: noraworld/diary-templates-assistant/.github/workflows/base.yml@main
    with:
      search_query: "housework 家事"
      template_name: "laundry"
      template_repo: "noraworld/diary-templates"
      version: "0.1.1"
    secrets:
      token: ${{ secrets.GH_TOKEN }}
