name: '251: 🎓🎧 リスニング'

on:
  workflow_dispatch:
    inputs:
      category:
        required: true
        description: '種別'
        type: choice
        options:
          - ''
          - '自由なアクティブ・イマージョン'
          - '受動的なリスニング'
        default: '自由なアクティブ・イマージョン'
      material:
        required: true
        description: '教材（リンク付き）'
        type: string
      subtitle:
        required: false
        description: '字幕の有無'
        type: choice
        options:
          - ''
          - 'なし'
          - 'あり'
          - '最初なし（あとからあり）'
      comprehension:
        required: false
        description: '理解度'
        type: choice
        options:
          - ''
          - '☆☆☆☆☆☆☆☆☆☆'
          - '★☆☆☆☆☆☆☆☆☆'
          - '★★☆☆☆☆☆☆☆☆'
          - '★★★☆☆☆☆☆☆☆'
          - '★★★★☆☆☆☆☆☆'
          - '★★★★★☆☆☆☆☆'
          - '★★★★★★☆☆☆☆'
          - '★★★★★★★☆☆☆'
          - '★★★★★★★★☆☆'
          - '★★★★★★★★★☆'
          - '★★★★★★★★★★'
      analysis:
        required: false
        description: '分析'
        type: string
      knowledge:
        required: false
        description: '学び'
        type: string
      impression:
        required: false
        description: '所感'
        type: string

jobs:
  listening:
    uses: noraworld/diary-templates-assistant/.github/workflows/base.yml@main
    with:
      search_query: "listening リスニング"
      template_name: "listening"
      template_repo: "noraworld/diary-templates"
      version: "0.2.0"
    secrets:
      token: ${{ secrets.GH_TOKEN }}
