name: 'aαа: 🚀🌱 瞑想'

on:
  workflow_dispatch:
    inputs:
      minutes:
        required: true
        description: '分'
        type: number
      seconds:
        required: true
        description: '秒'
        type: number
      thoughts:
        required: false
        description: '集中'
        type: string
      sensation:
        required: false
        description: '身体感覚'
        type: string
      feelings:
        required: false
        description: '気分'
        type: string
      impression:
        required: false
        description: 'メモ'
        type: string
      focused:
        required: true
        description: '集中度'
        type: choice
        options:
          - ''
          - '☆☆☆☆☆☆☆☆☆☆'
          - '★☆☆☆☆☆☆☆☆☆'
          - '★★☆☆☆☆☆☆☆☆'
          - '★★★☆☆☆☆☆☆☆'
          - '★★★★☆☆☆☆☆☆'
          - '★★★★★☆☆☆☆☆'
          - '★★★★★★☆☆☆☆'
          - '★★★★★★★☆☆☆'
          - '★★★★★★★★☆☆'
          - '★★★★★★★★★☆'
          - '★★★★★★★★★★'
      relaxed:
        required: true
        description: 'リラ度'
        type: choice
        options:
          - ''
          - '☆☆☆☆☆☆☆☆☆☆'
          - '★☆☆☆☆☆☆☆☆☆'
          - '★★☆☆☆☆☆☆☆☆'
          - '★★★☆☆☆☆☆☆☆'
          - '★★★★☆☆☆☆☆☆'
          - '★★★★★☆☆☆☆☆'
          - '★★★★★★☆☆☆☆'
          - '★★★★★★★☆☆☆'
          - '★★★★★★★★☆☆'
          - '★★★★★★★★★☆'
          - '★★★★★★★★★★'
      mood:
        required: true
        description: '気分度'
        type: choice
        options:
          - ''
          - '☆☆☆☆☆☆☆☆☆☆'
          - '★☆☆☆☆☆☆☆☆☆'
          - '★★☆☆☆☆☆☆☆☆'
          - '★★★☆☆☆☆☆☆☆'
          - '★★★★☆☆☆☆☆☆'
          - '★★★★★☆☆☆☆☆'
          - '★★★★★★☆☆☆☆'
          - '★★★★★★★☆☆☆'
          - '★★★★★★★★☆☆'
          - '★★★★★★★★★☆'
          - '★★★★★★★★★★'
      category:
        required: true
        description: '種別'
        type: choice
        options:
          - ''
          - '呼吸瞑想'
          - '慈悲の瞑想（通常版）'
          - '慈悲の瞑想（カスタム版）'
          - 'オープンモニタリング'
        # default: '呼吸瞑想'

jobs:
  meditation:
    uses: noraworld/diary-templates-assistant/.github/workflows/base.yml@main
    with:
      search_query: "meditation 瞑想"
      template_name: "meditation"
      template_repo: "noraworld/diary-templates"
      version: "0.2.0"
    secrets:
      token: ${{ secrets.GH_TOKEN }}
