name: '522: 🍀✨ 慰労記録 / ポジティブ'

on:
  workflow_dispatch:
    inputs:
      positive1:
        required: true
        description: 'ポジティブ 1'
        type: string
      positive2:
        required: false # was true
        description: 'ポジティブ 2'
        type: string
      positive3:
        required: false # was true
        description: 'ポジティブ 3'
        type: string
      positive4:
        required: false # was true
        description: 'ポジティブ 4'
        type: string
      positive5:
        required: false
        description: 'ポジティブ 5'
        type: string
      positive6:
        required: false
        description: 'ポジティブ 6'
        type: string
      positive7:
        required: false
        description: 'ポジティブ 7'
        type: string
      positive8:
        required: false
        description: 'ポジティブ 8'
        type: string
      positive9:
        required: false
        description: 'ポジティブ 9'
        type: string
      positive10:
        required: false
        description: 'ポジティブ 10'
        type: string

jobs:
  positive:
    uses: noraworld/diary-templates-assistant/.github/workflows/base.yml@main
    with:
      search_query: "esteem 慰労記録"
      template_name: "positive"
      template_repo: "noraworld/diary-templates"
      version: "0.2.0"
    secrets:
      token: ${{ secrets.GH_TOKEN }}
