name: '131: 🚀🪜 ワンステップチャレンジ' # https://chatgpt.com/share/6942cb5d-f1d4-8004-961a-41cbb77301ce

on:
  workflow_dispatch:
    inputs:
      activity1:
        required: true
        description: '今日、触れたこと 1（タスクあればリンク付き）'
        type: string
      activity2:
        required: false
        description: '今日、触れたこと 2（なければ書かなくて OK！）'
        type: string
      activity3:
        required: false
        description: '今日、触れたこと 3（なければ書かなくて OK！）'
        type: string
      activity4:
        required: false
        description: '今日、触れたこと 4（なければ書かなくて OK！）'
        type: string
      mode:
        required: true
        description: '今日は、どう進めた？'
        type: choice
        options:
          - ''
          - '時間'
          - 'ゴール'
          - '時間 & ゴール'
      # duration / milestone 合体版
      # 入力のときに一つで済むので楽だが記録の精度が落ちる
      #
      # extent:
      #   required: true
      #   description: '今日、どれくらい触れた？'
      #   type: choice
      #   options:
      #     - ''
      #     - '5'
      #     - '10'
      #     - '20'
      #     - '40'
      #     - '60'
      #     - '触れた'
      #     - '一区切り'
      #     - 'ひとつ終えた'
      milestone:
        required: false
        description: '今日は、どこまで進んだ？'
        type: choice
        options:
          - ''
          - '触れた'
          - '一区切り'
          - 'ひとつ終えた'
      duration:
        required: false
        description: '1 セッションの長さ（分）'
        type: choice
        options:
          - '20'
          - ''
          - '5'
          - '10'
          - '15'
          # - '20'
          - '25'
          - '30'
      sessions:
        required: false
        description: '今日は、何セッション触れた？'
        type: number # 'choice' にすると 2.25 とか入れづらい（「全端数用意するんか？」ってなる）
      note:
        required: false
        description: '今日のひとこと'
        type: string
      engagement:
        required: true
        description: '今日は、自分のやりたいことに一歩触れた？'
        type: boolean
      #
      # 振り返り / 改善点 / 反省 / 目標 / 評価 / モチベーション などは入れないこと（重要）
      #   https://chatgpt.com/share/6942cb5d-f1d4-8004-961a-41cbb77301ce
      #

jobs:
  progress:
    uses: noraworld/diary-templates-assistant/.github/workflows/base.yml@main
    with:
      search_query: "progress ワンステップチャレンジ"
      template_name: "progress"
      template_repo: "noraworld/diary-templates"
      version: "0.1.2"
    secrets:
      token: ${{ secrets.GH_TOKEN }}
