name: '221: 🎓🗣️ 発音練習'

on:
  workflow_dispatch:
    inputs:
      material:
        required: true
        description: '教材'
        type: choice
        options:
          - ''
          - 'BoldVoice'
          - 'ELSA Speak'
      streaks:
        required: true
        description: '連続日数'
        type: number
      points:
        required: true
        description: '経験値・星'
        type: number
      minutes:
        required: true
        description: '分'
        type: number
      activeness:
        required: true
        description: '積極性'
        type: choice
        options:
          - ''
          - '☆☆☆☆☆☆☆☆☆☆'
          - '★☆☆☆☆☆☆☆☆☆'
          - '★★☆☆☆☆☆☆☆☆'
          - '★★★☆☆☆☆☆☆☆'
          - '★★★★☆☆☆☆☆☆'
          - '★★★★★☆☆☆☆☆'
          - '★★★★★★☆☆☆☆'
          - '★★★★★★★☆☆☆'
          - '★★★★★★★★☆☆'
          - '★★★★★★★★★☆'
          - '★★★★★★★★★★'
      workmanship:
        required: true
        description: '出来'
        type: choice
        options:
          - ''
          - '☆☆☆☆☆☆☆☆☆☆'
          - '★☆☆☆☆☆☆☆☆☆'
          - '★★☆☆☆☆☆☆☆☆'
          - '★★★☆☆☆☆☆☆☆'
          - '★★★★☆☆☆☆☆☆'
          - '★★★★★☆☆☆☆☆'
          - '★★★★★★☆☆☆☆'
          - '★★★★★★★☆☆☆'
          - '★★★★★★★★☆☆'
          - '★★★★★★★★★☆'
          - '★★★★★★★★★★'
      impression:
        required: false
        description: '感想・その他'
        type: string

jobs:
  pronunciation:
    uses: noraworld/diary-templates-assistant/.github/workflows/base.yml@main
    with:
      search_query: "pronunciation 発音練習"
      template_name: "pronunciation"
      template_repo: "noraworld/diary-templates"
      version: "0.2.1"
    secrets:
      token: ${{ secrets.GH_TOKEN }}
