name: '211: 🎓📚 読書'

on:
  workflow_dispatch:
    inputs:
      candidate:
        required: false
        description: '（確認用）'
        type: choice
        default: ''
        # MEMO:
        #   - コメントテンプレートには含まれず記録には残らないため常に空欄にすること（空欄にしないと JSON には自動的に記録されてチグハグなデータになってしまう）
        #   - 読んだ書籍のすべてをこのリストに加える必要はない（特に薄いマンガなどはすぐに読み終わって次に進むので無理に登録する必要はない）
        options:
          - ''
          - '哲学的な何か、あと科学とか'
          - '史上最強の哲学入門'
          - '史上最強の哲学入門 東洋の哲人たち'
          - '反応しない練習'
          - '無（最高の状態）'
          - '考えすぎない練習'
          - '会社を辞めて週休3日生活しています'
          - '真・韓国の歴史 なぜ「反日」を捨てられないのか'
          - '自分とか、ないから。教養としての東洋哲学'
          - '天皇の日本史'
          - '自己肯定感の教科書'
          - '働かない勇気'
      title:
        required: true
        description: '書籍名'
        type: string
        # MEMO: いま読んでいる書籍がしばらく続く場合はここにデフォルト値を設定しておくと便利
        default: ''
      percent:
        required: true
        description: '読了率 (%)'
        type: number
      impression:
        required: false
        description: '感想・学び'
        type: string
      sample:
        required: true
        description: 'サンプル'
        type: boolean
        default: false
      unlimited:
        required: true
        description: '読み放題'
        type: boolean
        default: false
      reread:
        required: true
        description: '読み返し'
        type: boolean
        default: false
      partial:
        required: true
        description: '部分読み'
        type: boolean
        default: false
      timer:
        required: false
        description: 'タイマー（分）'
        type: choice
        options:
          - ''
          - '5'
          - '10'
          - '15'
          - '20'
          - '25'
          - '30'
          - '35'
          - '40'
          - '45'
          - '50'
          - '55'
          - '60'

jobs:
  reading:
    uses: noraworld/diary-templates-assistant/.github/workflows/base.yml@main
    with:
      search_query: "reading 読書"
      template_name: "reading"
      template_repo: "noraworld/diary-templates"
      version: "0.1.7"
    secrets:
      token: ${{ secrets.GH_TOKEN }}
