name: '511: 🍀🎯 心構え'

on:
  workflow_dispatch:
    inputs:
      legal:
        required: true
        description: '見ずに一括でチェックを付ける不正をしていない？'
        type: choice
        options:
          - ''
          - 'はい'
      resolved:
        required: true
        description: '心構えを肝に銘じた？'
        type: choice
        options:
          - ''
          - 'はい'
      impression:
        required: false
        description: '所感'
        type: string

jobs:
  readiness:
    uses: noraworld/diary-templates-assistant/.github/workflows/base.yml@main
    with:
      search_query: "readiness 心構え"
      template_name: "readiness"
      template_repo: "noraworld/diary-templates"
      version: "0.2.0"
    secrets:
      token: ${{ secrets.GH_TOKEN }}
