name: '211: 🎓📚 読書'

on:
  workflow_dispatch:
    inputs:
      title:
        required: true
        description: '書籍名'
        type: string
        default: '史上最強の哲学入門'
        # 読了リスト:
        #
        #   * 史上最強の哲学入門 東洋の哲人たち
        #   * 反応しない練習
        #   * 無（最高の状態）
        #   * 考えすぎない練習
        #   * 会社を辞めて週休3日生活しています
        #   * 真・韓国の歴史 なぜ「反日」を捨てられないのか
        #   * 自分とか、ないから。教養としての東洋哲学
        #   * 天皇の日本史
        #   * 自己肯定感の教科書
        #   * 働かない勇気
        #
      sample:
        required: true
        description: 'サンプル'
        type: boolean
        default: false
      percent:
        required: true
        description: '読了率 (%)'
        type: number
      timer:
        required: false
        description: 'タイマー（分）'
        type: choice
        options:
          - ''
          - '20'
          - '5'
          - '10'
          - '15'
          - '25'
          - '30'
          - '35'
          - '40'
          - '45'
          - '50'
          - '55'
          - '60'
      impression:
        required: false
        description: '感想・学び'
        type: string

jobs:
  reading:
    uses: noraworld/diary-templates-assistant/.github/workflows/base.yml@main
    with:
      search_query: "reading 読書"
      template_name: "reading"
      template_repo: "noraworld/diary-templates"
      version: "0.1.4"
    secrets:
      token: ${{ secrets.GH_TOKEN }}
