name: '531: 🍀💭 振り返り'

on:
  workflow_dispatch:
    inputs:
      timeline:
        required: false
        description: 'タイムラインへの記録'
        type: string
      motivation:
        required: true
        description: 'プライベートタスクのやる気'
        type: choice
        options:
          - ''
          - '☆☆☆☆☆☆☆☆☆☆'
          - '★☆☆☆☆☆☆☆☆☆'
          - '★★☆☆☆☆☆☆☆☆'
          - '★★★☆☆☆☆☆☆☆'
          - '★★★★☆☆☆☆☆☆'
          - '★★★★★☆☆☆☆☆'
          - '★★★★★★☆☆☆☆'
          - '★★★★★★★☆☆☆'
          - '★★★★★★★★☆☆'
          - '★★★★★★★★★☆'
          - '★★★★★★★★★★'
      productivity:
        required: true
        description: 'プライベートタスクの生産性'
        type: choice
        options:
          - ''
          - '☆☆☆☆☆☆☆☆☆☆'
          - '★☆☆☆☆☆☆☆☆☆'
          - '★★☆☆☆☆☆☆☆☆'
          - '★★★☆☆☆☆☆☆☆'
          - '★★★★☆☆☆☆☆☆'
          - '★★★★★☆☆☆☆☆'
          - '★★★★★★☆☆☆☆'
          - '★★★★★★★☆☆☆'
          - '★★★★★★★★☆☆'
          - '★★★★★★★★★☆'
          - '★★★★★★★★★★'
      readiness:
        required: true
        description: '心構えは意識できた？'
        type: boolean
      retrospective:
        required: false
        description: '今日の振り返り'
        type: string

jobs:
  retrospective:
    uses: noraworld/diary-templates-assistant/.github/workflows/base.yml@main
    with:
      search_query: "retrospective 振り返り"
      template_name: "retrospective"
      template_repo: "noraworld/diary-templates"
      version: "0.2.0"
    secrets:
      token: ${{ secrets.GH_TOKEN }}

  timeline:
    if: ${{ inputs.timeline != '' }}
    uses: noraworld/diary-templates-assistant/.github/workflows/timeline.yml@main
    secrets:
      token: ${{ secrets.GH_TOKEN }}
