name: '641: 🧹🛁 入浴記録'

on:
  workflow_dispatch:
    inputs:
      impression:
        required: false
        description: '所感'
        type: string
      timer:
        required: false
        description: 'タイマー（分）'
        type: choice
        options:
          - '20'
          - '' # 長さを計測していない場合はデフォルトを外すため
          - '5'
          - '10'
          - '15'
          - '25'
          - '30'
          - '35'
          - '40'
          - '45'
          - '50'
          - '55'
          - '60'
        default: '20'
      minutes:
        required: false
        description: '分'
        type: number
      seconds:
        required: false
        description: '秒'
        type: number
      toner:
        required: true
        description: '化粧水'
        type: boolean
      shaved:
        required: true
        description: '髭剃り'
        type: boolean
      pubes:
        required: true
        description: '下毛処理'
        type: boolean
      shampoo:
        required: true
        description: 'シャンプー'
        type: boolean
      bathed:
        required: true
        description: '洗体'
        type: boolean
      bath:
        required: true
        description: '入浴'
        type: boolean

jobs:
  shower:
    uses: noraworld/diary-templates-assistant/.github/workflows/base.yml@main
    with:
      search_query: "shower 入浴記録"
      template_name: "shower"
      template_repo: "noraworld/diary-templates"
      version: "0.1.1"
    secrets:
      token: ${{ secrets.GH_TOKEN }}
