name: '313: 🌿💤 睡眠記録 / パラメータ'

on:
  workflow_dispatch:
    inputs:
      impression:
        required: false
        description: '所感'
        type: string
      sleep:
        required: true
        description: '合計睡眠'
        type: choice
        options:
          - ''
          - '😴 最適'
          - '🙂 良好'
          - '😐 適度'
          - '😵 注意'
      efficiency:
        required: true
        description: '効率'
        type: choice
        options:
          - ''
          - '😴 最適'
          - '🙂 良好'
          - '😐 適度'
          - '😵 注意'
      restfulness:
        required: true
        description: '安眠度'
        type: choice
        options:
          - ''
          - '😴 最適'
          - '🙂 良好'
          - '😐 適度'
          - '😵 注意'
      rem:
        required: true
        description: 'レム睡眠'
        type: choice
        options:
          - ''
          - '😴 最適'
          - '🙂 良好'
          - '😐 適度'
          - '😵 注意'
      deep:
        required: true
        description: '深い睡眠'
        type: choice
        options:
          - ''
          - '😴 最適'
          - '🙂 良好'
          - '😐 適度'
          - '😵 注意'
      latency:
        required: true
        description: '入眠潜時'
        type: choice
        options:
          - ''
          - '😴 最適'
          - '🙂 良好'
          - '😐 適度'
          - '😵 注意'
      timing:
        required: true
        description: 'タイミング'
        type: choice
        options:
          - ''
          - '😴 最適'
          - '🙂 良好'
          - '😐 適度'
          - '😵 注意'
      merged:
        required: true
        description: '前日分とのマージ有無'
        type: boolean
        default: false

jobs:
  sleep:
    uses: noraworld/diary-templates-assistant/.github/workflows/base.yml@main
    with:
      search_query: "sleep 睡眠記録"
      template_name: "sleep-parameters"
      template_repo: "noraworld/diary-templates"
      version: "0.1.5"
    secrets:
      token: ${{ secrets.GH_TOKEN }}
