name: '312: 🌿💤 睡眠記録 / 基本情報'

on:
  workflow_dispatch:
    inputs:
      impression:
        required: false
        description: '所感'
        type: string
      sleep_hours:
        required: true
        description: '合計睡眠（時）'
        type: number
      sleep_minutes:
        required: true
        description: '合計睡眠（分）'
        type: number
      bed_hours:
        required: true
        description: 'ベッド時間（時）'
        type: number
      bed_minutes:
        required: true
        description: 'ベッド時間（分）'
        type: number
      efficiency:
        required: true
        description: '睡眠効率 (%)'
        type: number
      bpm:
        required: true
        description: '安静時心拍数 (bpm)'
        type: number
      score:
        required: true
        description: '睡眠スコア'
        type: number
      merged:
        required: true
        description: '前日分とのマージ有無'
        type: boolean
        default: false

jobs:
  sleep:
    uses: noraworld/diary-templates-assistant/.github/workflows/base.yml@main
    with:
      search_query: "sleep 睡眠記録"
      template_name: "sleep-basic"
      template_repo: "noraworld/diary-templates"
      version: "0.2.1"
    secrets:
      token: ${{ secrets.GH_TOKEN }}
