name: '311: 🌿💤 睡眠記録 / 主観情報'

on:
  workflow_dispatch:
    inputs:
      night:
        required: true
        description: '主観就寝時刻'
        type: string
      morning:
        required: true
        description: '主観起床時刻'
        type: string
      window:
        required: false
        description: '就寝寝起考察'
        type: string
      mood:
        required: true
        description: '寝起気分'
        type: choice
        options:
          - ''
          - '☆☆☆☆☆☆☆☆☆☆'
          - '★☆☆☆☆☆☆☆☆☆'
          - '★★☆☆☆☆☆☆☆☆'
          - '★★★☆☆☆☆☆☆☆'
          - '★★★★☆☆☆☆☆☆'
          - '★★★★★☆☆☆☆☆'
          - '★★★★★★☆☆☆☆'
          - '★★★★★★★☆☆☆'
          - '★★★★★★★★☆☆'
          - '★★★★★★★★★☆'
          - '★★★★★★★★★★'
      emotion:
        required: false
        description: '気分考察'
        type: string
      dream:
        required: false
        description: '夢日記'
        type: string
      impression:
        required: false
        description: '所感'
        type: string

jobs:
  sleep:
    uses: noraworld/diary-templates-assistant/.github/workflows/base.yml@main
    with:
      search_query: "sleep 睡眠記録"
      template_name: "sleep-subjective"
      template_repo: "noraworld/diary-templates"
      version: "0.1.1"
    secrets:
      token: ${{ secrets.GH_TOKEN }}
