name: '314: 🌿💤 睡眠記録 / 就寝・起床時刻'

on:
  workflow_dispatch:
    inputs:
      night1:
        required: true
        description: '就寝時刻 1'
        type: string
      morning1:
        required: true
        description: '起床時刻 1'
        type: string
      night2:
        required: false
        description: '就寝時刻 2'
        type: string
      morning2:
        required: false
        description: '起床時刻 2'
        type: string
      impression:
        required: false
        description: '所感'
        type: string
      merged:
        required: true
        description: '前日分とのマージ有無'
        type: boolean
        default: false

jobs:
  sleep:
    uses: noraworld/diary-templates-assistant/.github/workflows/base.yml@main
    with:
      search_query: "sleep 睡眠記録"
      template_name: "sleep-bedtime"
      template_repo: "noraworld/diary-templates"
      version: "0.1.0"
    secrets:
      token: ${{ secrets.GH_TOKEN }}
