name: '315: 🌿💤 睡眠記録 / その他の情報'

on:
  workflow_dispatch:
    inputs:
      stress1:
        required: true
        description: '昨日のストレス値'
        type: choice
        options:
          - ''
          - '修復'
          - '普通'
          - '多い'
          - '体表温の上昇'
          - '概要なし'
      reason1:
        required: false
        description: '考察'
        type: string
      resilience2:
        required: true
        description: 'レジリエンス'
        type: choice
        options:
          - ''
          - '絶好調'
          - '好調'
          - '普通'
          - 'やや不足'
          - '不足'
          - 'データなし'
      reason2:
        required: false
        description: '考察'
        type: string
      impression:
        required: false
        description: '所感'
        type: string
      stressed_hours1:
        required: true
        description: 'ストレス時間（時）'
        type: number
      stressed_minutes1:
        required: true
        description: 'ストレス時間（分）'
        type: number
      recovery_hours1:
        required: true
        description: '回復時間（時）'
        type: number
      recovery_minutes1:
        required: true
        description: '回復時間（分）'
        type: number
      tendency2:
        required: true
        description: '傾向'
        type: choice
        options:
          - ''
          - '上昇'
          - '変化なし'
          - '下降'

jobs:
  sleep:
    uses: noraworld/diary-templates-assistant/.github/workflows/base.yml@main
    with:
      search_query: "sleep 睡眠記録"
      template_name: "sleep-details"
      template_repo: "noraworld/diary-templates"
      version: "0.2.3"
    secrets:
      token: ${{ secrets.GH_TOKEN }}
