name: Templates Closer

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Add done label to close issues
        run: |
          issue_templates_title=$(gh issue list --repo "noraworld/diary-templates" --json title --jq .[].title)
          issue_templates_count=$(echo "$issue_templates_title" | wc -l)
          issue_templates_matched_count=$(echo "$issue_templates_title" | grep -c "$(date '+%Y-%m-%d')")

          if [ "$issue_templates_count" != "$issue_templates_matched_count" ]; then
            echo "DEBUG: the number of diary templates:         $issue_templates_count" >&2
            echo "DEBUG: the number of matched diary templates: $issue_templates_matched_count" >&2
            echo "Some of or all of the diary templates issue title does not match yesterday's date." >&2
            exit 1
          fi

          gh issue list --repo "noraworld/diary-templates" | awk '{ print $1 }' | xargs -I {} gh issue edit {} --repo "noraworld/diary-templates" --add-label "done"
        shell: sh
        env:
          ### GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.token }}
