name: Templates Creator

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Create issues from templates
        run: |
          DIARY_ISSUE_NUMBER=$(gh issue list --repo "noraworld/diary" --limit 1 | awk '{ print $1 }')
          diary_issue_title=$(gh issue view --repo "noraworld/diary" --json title --jq .title "$DIARY_ISSUE_NUMBER")
          diary_issue_body=$(gh issue view --repo "noraworld/diary" --json body --jq .body "$DIARY_ISSUE_NUMBER")
          ISSUE_TITLE_LIST=$(gh issue list --repo "noraworld/diary-templates" --json title --jq .[].title)

          if [ "$diary_issue_title" != "$(date '+%Y-%m-%d' --date '1 day')" ]; then
            echo "DEBUG: diary issue title: $diary_issue_title" >&2
            echo "DEBUG: today's date:      $(date '+%Y-%m-%d' --date '1 day')" >&2
            echo "The diary issue title does not match today's date." >&2
            exit 1
          fi

          for issue_template in .github/ISSUE_TEMPLATE/*; do
            title=$(grep "title: " "$issue_template"                              |
                    sed -e 's/^title: //g'                                        |
                    sed -e "s/[\"\']//g"                                          |
                    sed -e "s/\[{{DATE}}\]/$(date '+%Y-%m-%d' --date '1 day')/g")

            if [ "$(echo "$ISSUE_TITLE_LIST" | grep -c "$title")" -ne 0 ]; then
              echo "It will be skipped because \"$title\" already exists." >&2
              continue
            fi

            body=$(sed -e '/^---$/,/^---$/d' "$issue_template")

            assignee=$(grep "assignees: " "$issue_template" |
                       sed -e 's/^assignees: //g'           |
                       sed -e "s/[\"\']//g")

            url=$(gh issue create                      \
                    --repo "noraworld/diary-templates" \
                    --title "$title"                   \
                    --body "$body"                     \
                    --assignee "$assignee")

            display_name=$(echo "$title" | cut -d '_' -f3)
            # https://chat.openai.com/share/0bb3dd50-70bb-4c09-8396-1f53824c3962
            escaped_url=$(echo "$url" | sed 's/[\^\$\.\/]/\\&/g')
            diary_issue_body=$(echo "$diary_issue_body" | sed -E "s/$display_name/\[$display_name\]\($escaped_url\)/g")
          done

          gh issue edit --repo "noraworld/diary" --body "$diary_issue_body" "$DIARY_ISSUE_NUMBER"
        shell: sh
        env:
          GH_TOKEN: ${{ secrets.token }}
