name: Templates Closer

on:
  # It is fine to perform it manually. Because it is idempotent, it does nothing if there are no open issues.
  ### workflow_dispatch:
  # The time must be BEFORE the current diary is closed and the new one is created.
  # https://github.com/noraworld/diary/blob/main/.github/workflows/issue-changer.yml
  ### schedule:
  ###   - cron: '30 22 * * *'
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Add done label to close issues
        run: |
          issue_templates_title=$(gh issue list --json title --jq .[].title)
          issue_templates_count=$(echo "$issue_templates_title" | wc -l)
          issue_templates_matched_count=$(echo "$issue_templates_title" | grep -c "$(date '+%Y-%m-%d')")

          if [ "$issue_templates_count" != "$issue_templates_matched_count" ]; then
            echo "DEBUG: the number of diary templates:         $issue_templates_count" >&2
            echo "DEBUG: the number of matched diary templates: $issue_templates_matched_count" >&2
            echo "Some of or all of the diary templates issue title does not match yesterday's date." >&2
            exit 1
          fi

          gh issue list | awk '{ print $1 }' | xargs -I {} gh issue edit {} --add-label "done"
        shell: sh
        env:
          ### GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.token }}
