name: Templates Closer

on:
  workflow_dispatch:
  # The time must be BEFORE the current diary is closed and the new one is created.
  # https://github.com/noraworld/diary/blob/main/.github/workflows/issue-changer.yml
  schedule:
    - cron: '0 21 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Add done label to open issues
        run: |
          gh issue list | awk '{ print $1 }' | xargs -I {} gh issue edit {} --add-label "done"
        shell: sh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
