name: Templates Linker

on:
  workflow_call:
    inputs:
      main_repo:
        required: true
        type: string
      template_repo:
        required: true
        type: string
      timezone:
        required: true
        type: string
    secrets:
      token:
        required: true
  workflow_dispatch:
    inputs:
      main_repo:
        required: true
        type: string
      template_repo:
        required: true
        type: string
      timezone:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Add link to each template
        run: |
          DIARY_ISSUE_NUMBER=$(gh issue list --repo "$MAIN_REPO" --limit 1 | awk '{ print $1 }')
          diary_issue_body=$(gh issue view --repo "$MAIN_REPO" --json body --jq .body "$DIARY_ISSUE_NUMBER")
          issue_list=$(gh issue list --repo "$TEMPLATE_REPO" --json title,url --template '{{range .}}{{.title}} {{.url}}{{"\n"}}{{end}}')

          echo "$issue_list" | while IFS= read -r line; do
            display_name=$(echo "$line" | awk '{ print $1 }' | cut -d '_' -f4)
            # https://chat.openai.com/share/0bb3dd50-70bb-4c09-8396-1f53824c3962
            escaped_url=$(echo "$line" | awk '{ print $2 }' | sed 's/[\^\$\.\/]/\\&/g')
            diary_issue_body=$(echo "$diary_issue_body" | sed -E "s/$display_name/\[$display_name\]\($escaped_url\)/g")
          done

          gh issue edit --repo "$MAIN_REPO" --body "$diary_issue_body" "$DIARY_ISSUE_NUMBER"
        env:
          GH_TOKEN: ${{ secrets.token || secrets.GH_TOKEN }}
          MAIN_REPO: ${{ inputs.main_repo }}
          TEMPLATE_REPO: ${{ inputs.template_repo }}
          TZ: ${{ inputs.timezone }}
