name: Templates Creator

on:
  workflow_call:
    inputs:
      main_repo:
        required: true
        type: string
      template_repo:
        required: true
        type: string
      issue_template_repo:
        required: true
        type: string
      timezone:
        required: true
        type: string
    outputs:
      succeeded:
        value: ${{ jobs.build.outputs.succeeded }}
    secrets:
      token:
        required: true
  workflow_dispatch:
    inputs:
      main_repo:
        required: true
        type: string
      template_repo:
        required: true
        type: string
      issue_template_repo:
        required: true
        type: string
      timezone:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      succeeded: ${{ steps.create.outputs.succeeded }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.issue_template_repo }}
          ref: main
          token: ${{ secrets.token || secrets.GH_TOKEN }}
          path: tmp

      - name: Create issues from templates
        id: create
        run: |
          DIARY_ISSUE=$(gh issue list --repo "$MAIN_REPO" --limit 1 --json number,url)
          DIARY_ISSUE_NUMBER=$(echo "$DIARY_ISSUE" | jq -r '.[0].number')
          DIARY_ISSUE_URL=$(echo "$DIARY_ISSUE" | jq -r '.[0].url')
          diary_issue_title=$(gh issue view --repo "$MAIN_REPO" --json title --jq .title "$DIARY_ISSUE_NUMBER")
          ISSUE_TITLE_LIST=$(gh issue list --repo "$TEMPLATE_REPO" --json title --jq .[].title)

          if [ "$diary_issue_title" != "$(date '+%Y-%m-%d' --date '0 day')" ]; then
            echo "DEBUG: diary issue title: $diary_issue_title" >&2
            echo "DEBUG: today's date:      $(date '+%Y-%m-%d' --date '0 day')" >&2
            echo "The diary issue title does not match today's date." >&2
            echo "succeeded=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          find tmp/.github/ISSUE_TEMPLATE -type f | while read -r issue_template; do
            raw_number=$(grep -m1 '^name:' "$issue_template" | sed -E 's/^name:[[:space:]]*([0-9]+)\..*/\1/')
            number=$((10#$raw_number))
            printf "%03d %s\n" "$number" "$issue_template"
          done | sort -nr | while read -r number issue_template; do
            title=$(grep "title: " "$issue_template"                              |
                    sed -e 's/^title: //g'                                        |
                    sed -e "s/[\"\']//g"                                          |
                    sed -e "s/\[{{DATE}}\]/$(date '+%Y-%m-%d' --date '0 day')/g")

            if [ "$(echo "$ISSUE_TITLE_LIST" | grep -c "$title")" -ne 0 ]; then
              echo "It will be skipped because \"$title\" already exists." >&2
              continue
            fi

            body=$(
              awk '
                NR==1 && $0 == "---" { in_header=1; next }
                in_header && $0 == "---" { in_header=0; next }
                !in_header
              ' "$issue_template" |
              sed -e "s|\[{{MAIN_REPO_TODAY_URL}}\]|$DIARY_ISSUE_URL|g" |
              sed -e "s/\[{{YESTERDAY_YEAR}}\]/$(date '+%Y' --date '1 day ago')/g" |
              sed -e "s/\[{{YESTERDAY_MONTH}}\]/$(date '+%m' --date '1 day ago')/g" |
              sed -e "s/\[{{YESTERDAY_DATE}}\]/$(date '+%Y-%m-%d' --date '1 day ago')/g"
            )

            assignee=$(grep "assignees: " "$issue_template" |
                       sed -e 's/^assignees: //g'           |
                       sed -e "s/[\"\']//g")

            label=$(grep "labels: " "$issue_template" |
                    sed -e 's/^labels: //g'           |
                    sed -e "s/[\"\']//g")

            url=$(gh issue create           \
                    --repo "$TEMPLATE_REPO" \
                    --title "$title"        \
                    --body "$body"          \
                    --assignee "$assignee"  \
                    --label "$label")

            # https://github.com/noraworld/diary-templates/actions/runs/12000592518/job/33477428100
            # https://syossan.hateblo.jp/entry/2022/12/24/124141
            sleep 2
          done

          echo "succeeded=true" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.token || secrets.GH_TOKEN }}
          MAIN_REPO: ${{ inputs.main_repo }}
          TEMPLATE_REPO: ${{ inputs.template_repo }}
          TZ: ${{ inputs.timezone }}
