# https://chatgpt.com/s/t_68a207be3ef08191aa756f8e74c30571 (in https://chatgpt.com/share/68a207ca-9710-8004-a8a0-9ece14105c1b)

name: Timeline

on:
  workflow_call:
    inputs:
      committer_email:
        required: false
        type: string
        default: mail@noraworld.com
      committer_name:
        required: false
        type: string
        default: Kosuke Aoki
      date:
        required: false
        type: string
        default: ''
      filepath:
        required: false
        type: string
        default: static/timeline.jsonl
      message_if_file_exists:
        required: false
        type: string
        default: Update <FILENAME>
      message_if_file_not_exists:
        required: false
        type: string
        default: Create <FILENAME>
      repo:
        required: false
        type: string
        default: noraworld/reserved-diary
    secrets:
      token:
        required: true
  workflow_dispatch:
    inputs:
      committer_email:
        required: true
        description: 'コミッターメールアドレス'
        type: string
        default: mail@noraworld.com
      committer_name:
        required: true
        description: 'コミッター名'
        type: string
        default: Kosuke Aoki
      date:
        required: false
        description: '日付'
        type: string
        default: ''
      filepath:
        required: true
        description: 'ファイルパス'
        type: string
        default: static/timeline.jsonl
      message_if_file_exists:
        required: true
        description: 'ファイル存在時コミットメッセージ'
        type: string
        default: Update <FILENAME>
      message_if_file_not_exists:
        required: true
        description: 'ファイル非存在時コミットメッセージ'
        type: string
        default: Create <FILENAME>
      repo:
        required: true
        description: '対象リポジトリ'
        type: choice
        options:
          - noraworld/reserved-diary
          - noraworld/private-diary
        default: noraworld/reserved-diary
      timeline:
        required: true
        description: 'タイムラインへの記録'
        type: string

jobs:
  build:
    uses: noraworld/diary-templates-assistant/.github/workflows/build-typescript.yml@main
    with:
      node-version: '23.11.0'
      out-dir: 'dist'

  run:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '23.11.0'
          cache: npm

      - name: Install runtime dependencies
        run: npm ci --omit=dev

      - name: Download compiled JS
        uses: actions/download-artifact@v4
        with:
          name: dist-js
          path: dist

      - name: Get date
        run: |
          if [ "${{ inputs.date }}" != "" ]; then
            DATE=${{ inputs.date }}
          else
            DATE=$(gh issue list --repo noraworld/reserved-diary --limit 1 --json title --jq '.[0].title')
          fi

          echo "DATE=$DATE" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.token || secrets.GH_TOKEN }}

      - name: Record timeline
        run: node dist/timeline.js
        env:
          COMMITTER_EMAIL:            ${{ inputs.committer_email }}
          COMMITTER_NAME:             ${{ inputs.committer_name }}
          DATE:                       ${{ env.DATE }}
          FILEPATH:                   ${{ inputs.filepath }}
          GH_TOKEN:                   ${{ secrets.token || secrets.GH_TOKEN }}
          MESSAGE_IF_FILE_EXISTS:     ${{ inputs.message_if_file_exists }}
          MESSAGE_IF_FILE_NOT_EXISTS: ${{ inputs.message_if_file_not_exists }}
          REPO:                       ${{ inputs.repo }}
