name: Update Day Off

on:
  workflow_call:
    inputs:
      date:
        required: true
        type: string
      fail_if_day_off:
        required: true
        type: boolean
        default: false
      gh_output_format:
        required: true
        type: boolean
        default: true
      timezone:
        required: true
        type: string
        default: 'Asia/Tokyo'
  workflow_dispatch:
    inputs:
      date:
        required: true
        description: 'Date (YYYY-MM-DD)'
        type: string
      fail_if_day_off:
        required: true
        description: 'Fail if day off'
        type: boolean
        default: false
      gh_output_format:
        required: true
        description: 'GitHub output'
        type: boolean
        default: true
      timezone:
        required: true
        description: 'Timezone'
        type: choice
        options:
          - ''
          - 'Etc/Universal'
          - 'Asia/Tokyo'
          - 'Australia/Sydney'
        default: 'Asia/Tokyo'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
          cache: 'pipenv'

      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python

      - name: Install packages
        run: pipenv install

      - name: Update day-off list
        run: |
          pipenv run python app/day-off.py append ${{ env.DATE }}

          if [ "$(git status --porcelain)" != "" ]; then
            git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"
            git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
            git add data/day-off.json
            git commit -m "Make ${{ env.DATE }} day off"
            git push -u origin main
          fi
        shell: sh
        env:
          DATE: ${{ inputs.date || github.event.inputs.date }}
          FAIL_IF_DAY_OFF: ${{ inputs.fail_if_day_off || github.event.inputs.fail_if_day_off }}
          GH_OUTPUT_FORMAT: ${{ inputs.gh_output_format || github.event.inputs.gh_output_format }}
          PYTHONPATH: .
          TZ: ${{ inputs.timezone || github.event.inputs.timezone }}
