name: '351: 🌿💧 排泄記録 / 排尿'

on:
  workflow_dispatch:
    inputs:
      amount:
        required: true
        description: '量'
        type: choice
        options:
          - ''
          - '100'
          - '150'
          - '200'
          - '250'
          - '300'
          - '350'
          - '400'
          - '450'
          - '500'
          - '550'
          - '600'
          - '650'
          - '700'
          - '750'
          - '800'
          - '850'
          - '900'
          - '950'
          - '1000'
      color:
        required: true
        description: '色'
        type: choice
        options:
          - ''
          - '透明'
          - 'レモン'
          - 'パイン'
          - 'みかん'
          - 'あんず'
          - 'チェリー'
          - 'コーラ'
          - 'ブルーハワイ'
      eyeballing:
        required: true
        description: '目分量'
        type: boolean
      impression:
        required: false
        description: 'メモ'
        type: string
      foam:
        required: true
        description: 'バブル'
        type: boolean
        default: true
      cloudy:
        required: true
        description: '濁り'
        type: boolean
      pain:
        required: true
        description: '痛み'
        type: boolean
      residuals:
        required: true
        description: '残尿感'
        type: boolean
      urgency:
        required: true
        description: '切迫感'
        type: boolean
      incontinence:
        required: true
        description: '失禁'
        type: boolean

jobs:
  urination:
    uses: noraworld/diary-templates-assistant/.github/workflows/base.yml@main
    with:
      search_query: "excretion 排泄記録"
      template_name: "urination"
      template_repo: "noraworld/diary-templates"
      version: "0.3.1"
    secrets:
      token: ${{ secrets.GH_TOKEN }}
