name: '231: 🎓📖 単語学習'

on:
  workflow_dispatch:
    inputs:
      progress:
        required: true
        description: '進捗率 (%)'
        type: number
      words:
        required: true
        description: '単語数 (words)'
        type: number
      practice:
        required: true
        description: '発音練習'
        type: boolean
        default: true
      points:
        required: true
        description: '経験値 (XP)'
        type: number
      streaks:
        required: true
        description: '連続日数 (streaks)'
        type: number
      minutes:
        required: true
        description: '分'
        type: number
      impression:
        required: false
        description: '感想・その他'
        type: string
      activeness:
        required: true
        description: '積極性'
        type: choice
        options:
          - ''
          - '☆☆☆☆☆☆☆☆☆☆'
          - '★☆☆☆☆☆☆☆☆☆'
          - '★★☆☆☆☆☆☆☆☆'
          - '★★★☆☆☆☆☆☆☆'
          - '★★★★☆☆☆☆☆☆'
          - '★★★★★☆☆☆☆☆'
          - '★★★★★★☆☆☆☆'
          - '★★★★★★★☆☆☆'
          - '★★★★★★★★☆☆'
          - '★★★★★★★★★☆'
          - '★★★★★★★★★★'
      material:
        required: true
        description: '教材'
        type: choice
        options:
          - ''
          - 'Distinction I'
          - 'Distinction II'
          - 'Distinction III'
          - 'Distinction IV'
          - 'Distinction V'
          - 'Distinction VI'
          - 'Distinction Structures'
          - 'Distinction 2000'
        default: 'Distinction VI'

jobs:
  vocabulary:
    uses: noraworld/diary-templates-assistant/.github/workflows/base.yml@main
    with:
      search_query: "vocabulary 単語学習"
      template_name: "vocabulary"
      template_repo: "noraworld/diary-templates"
      version: "0.2.2"
    secrets:
      token: ${{ secrets.GH_TOKEN }}
