name: Wage

on:
  workflow_dispatch:
    inputs:
      my_annual:
        required: true
        description: 'My annual salary'
        type: string
  workflow_call:
    inputs:
      my_annual:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install packages
        run: npm install

      - name: Insert wages
        run: node wage.js
        shell: sh
        env:
          GITHUB_TOKEN:       ${{ secrets.token || secrets.GH_TOKEN }}
          RESAS_API_KEY:      ${{ secrets.token || secrets.RESAS_API_KEY }}
          MY_ANNUAL:          ${{ inputs.my_annual || github.event.inputs.my_annual }}
          REPO:               'noraworld/daily-report-templates'
          SEARCH_QUERY:       '心構え'
