name: Wait Closed

on:
  workflow_call:
    inputs:
      maximum_attempt_threshold:
        default: 30
        required: false
        type: string
      sleep_interval:
        default: 10
        required: false
        type: string
      template_repo:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Check if all of the templates have successfully been closed
        run: |
          attempt=0

          # Wait for all of the templates to be closed.
          while [ "$(gh issue list --repo "$TEMPLATE_REPO" | wc -l)" -ne 0 ]; do
            # The shorter the sleep interval is, the more frequently the error below may occur.
            #   GraphQL: was submitted too quickly (createIssue)
            sleep $SLEEP_INTERVAL

            attempt=$(($attempt + 1))
            if [ "$attempt" -gt "$MAXIMUM_ATTEMPT_THRESHOLD" ]; then
              echo "Timeout period exceeded." >&2
              exit 1
            fi
          done

          # To avoid causing the error. Just in case.
          sleep $SLEEP_INTERVAL
        shell: sh
        env:
          GH_TOKEN: ${{ secrets.token }}
          MAXIMUM_ATTEMPT_THRESHOLD: ${{ inputs.maximum_attempt_threshold }}
          SLEEP_INTERVAL: ${{ inputs.sleep_interval }}
          TEMPLATE_REPO: ${{ inputs.template_repo }}
