name: '154: 🚀👟 ウォーキング'

on:
  workflow_dispatch:
    inputs:
      motivation:
        required: true
        description: '外出意欲'
        type: choice
        options:
          - ''
          - '☆☆☆☆☆☆☆☆☆☆'
          - '★☆☆☆☆☆☆☆☆☆'
          - '★★☆☆☆☆☆☆☆☆'
          - '★★★☆☆☆☆☆☆☆'
          - '★★★★☆☆☆☆☆☆'
          - '★★★★★☆☆☆☆☆'
          - '★★★★★★☆☆☆☆'
          - '★★★★★★★☆☆☆'
          - '★★★★★★★★☆☆'
          - '★★★★★★★★★☆'
          - '★★★★★★★★★★'
      mood:
        required: true
        description: '気分度'
        type: choice
        options:
          - ''
          - '☆☆☆☆☆☆☆☆☆☆'
          - '★☆☆☆☆☆☆☆☆☆'
          - '★★☆☆☆☆☆☆☆☆'
          - '★★★☆☆☆☆☆☆☆'
          - '★★★★☆☆☆☆☆☆'
          - '★★★★★☆☆☆☆☆'
          - '★★★★★★☆☆☆☆'
          - '★★★★★★★☆☆☆'
          - '★★★★★★★★☆☆'
          - '★★★★★★★★★☆'
          - '★★★★★★★★★★'
      feeling:
        required: false
        description: '気分の変化'
        type: string
      loving_kindness:
        required: true
        description: '慈経行'
        type: boolean
      awe:
        required: true
        description: '畏経行'
        type: boolean
      awe_inspiring:
        required: false
        description: '景色・超越性・畏怖'
        type: string

      weather:
        required: true
        description: '天気'
        type: choice
        options:
          - ''
          - '晴れ'
          - 'くもり'
          - '雨'
      temperature:
        required: true
        description: '体感気温'
        type: choice
        options:
          - ''
          - '暑い'
          - '蒸し暑い'
          - '少し蒸し暑い'
          - '暖かい'
          - '温暖'
          - '普通'
          - '少し涼しい'
          - '涼しい'
          - '少し肌寒い'
          - '肌寒い'
          - '寒い'
          - 'とても寒い'

      destination:
        required: true
        description: '行き先'
        type: string
      hours:
        required: true
        description: '時間'
        type: number
      minutes:
        required: true
        description: '分'
        type: number
      seconds:
        required: true
        description: '秒'
        type: number
      distance:
        required: true
        description: '距離（km）'
        type: number
      burned:
        required: true
        description: '消費カロリー'
        type: number
      pace_minutes:
        required: true
        description: '平均ペース（分）'
        type: number
      pace_seconds:
        required: true
        description: '平均ペース（秒）'
        type: number
      heart:
        required: true
        description: '平均心拍数'
        type: number
      impression:
        required: false
        description: '所感'
        type: string

      mail:
        required: false
        description: '郵便物'
        type: string
      mail_check:
        required: true
        description: '郵便物の確認'
        type: boolean
      mail_collection:
        required: true
        description: '郵便物の回収'
        type: boolean
      garbage:
        required: true
        description: 'ゴミ捨て'
        type: boolean
      music:
        required: true
        description: '音楽'
        type: boolean
      pokemon:
        required: true
        description: 'Pokémon GO'
        type: boolean

jobs:
  walking:
    uses: noraworld/diary-templates-assistant/.github/workflows/base.yml@main
    with:
      search_query: "walking ウォーキング"
      template_name: "walking"
      template_repo: "noraworld/diary-templates"
      version: "0.2.0"
    secrets:
      token: ${{ secrets.GH_TOKEN }}
