name: '141: 🚀👟 ウォーキング'

on:
  workflow_dispatch:
    inputs:
      weather:
        required: true
        description: '天気'
        type: choice
        options:
          - ''
          - '晴れ'
          - 'くもり'
          - '雨'
      temperature:
        required: true
        description: '体感気温'
        type: choice
        options:
          - ''
          - 'とても寒い'
          - '寒い'
          - '肌寒い'
          - '少し肌寒い'
          - '涼しい'
          - '少し涼しい'
          - '普通'
          - '温暖'
          - '暖かい'
          - '少し蒸し暑い'
          - '蒸し暑い'
          - '暑い'
      destination:
        required: true
        description: '行き先'
        type: string
      hours:
        required: true
        description: '時間'
        type: number
      minutes:
        required: true
        description: '分'
        type: number
      seconds:
        required: true
        description: '秒'
        type: number
      distance:
        required: true
        description: '距離'
        type: number
      pace:
        required: true
        description: '平均ペース'
        type: number
      heart:
        required: true
        description: '平均心拍数'
        type: number
      burned:
        required: true
        description: '消費カロリー'
        type: number
      motivation:
        required: true
        description: '外出意欲'
        type: choice
        options:
          - ''
          - '☆☆☆☆☆☆☆☆☆☆'
          - '★☆☆☆☆☆☆☆☆☆'
          - '★★☆☆☆☆☆☆☆☆'
          - '★★★☆☆☆☆☆☆☆'
          - '★★★★☆☆☆☆☆☆'
          - '★★★★★☆☆☆☆☆'
          - '★★★★★★☆☆☆☆'
          - '★★★★★★★☆☆☆'
          - '★★★★★★★★☆☆'
          - '★★★★★★★★★☆'
          - '★★★★★★★★★★'
      mood:
        required: true
        description: '気分度'
        type: choice
        options:
          - ''
          - '☆☆☆☆☆☆☆☆☆☆'
          - '★☆☆☆☆☆☆☆☆☆'
          - '★★☆☆☆☆☆☆☆☆'
          - '★★★☆☆☆☆☆☆☆'
          - '★★★★☆☆☆☆☆☆'
          - '★★★★★☆☆☆☆☆'
          - '★★★★★★☆☆☆☆'
          - '★★★★★★★☆☆☆'
          - '★★★★★★★★☆☆'
          - '★★★★★★★★★☆'
          - '★★★★★★★★★★'
      garbage:
        required: true
        description: 'ゴミ捨て'
        type: boolean
      mail:
        required: true
        description: '郵便物'
        type: string
      scenery:
        required: true
        description: '今回見たいい景色'
        type: string
      mood:
        required: true
        description: '気分の変化'
        type: string
      impression:
        required: false
        description: '所感'
        type: string
      pokemon:
        required: true
        description: 'Pokémon GO'
        type: boolean
      mail_check:
        required: true
        description: '郵便物の確認'
        type: boolean
      mail_collection:
        required: true
        description: '郵便物の回収'
        type: boolean
      negative:
        required: true
        description: 'ネガティブな意味で他人に意識を向けない努力'
        type: boolean
      positive:
        required: true
        description: 'いい景色や新たな発見にポジティブな意識を向ける努力'
        type: boolean

jobs:
  walking:
    uses: noraworld/diary-templates-assistant/.github/workflows/base.yml@main
    with:
      search_query: "walking ウォーキング"
      template_name: "walking"
      template_repo: "noraworld/diary-templates"
      version: "0.1.0"
    secrets:
      token: ${{ secrets.GH_TOKEN }}
